version: "3.9"

services:
  netlify-cli:
    platform: linux/amd64  ## Deno doesn't have executable for Linux aarch64
    image: ghcr.io/williamjacksn/netlify-cli:13.1.1
    user: root
    environment:
      NETLIFY_SITE_ID: ${NETLIFY_SITE_ID}
      NETLIFY_AUTH_TOKEN: ${NETLIFY_AUTH_TOKEN}
    volumes:
      - .:/project
